---
- name: Speiseplan Benachrichtigung
  hosts: all
  connection: local
  # gather_facts: false

  tasks:
    - name: Hole die Plan Daten
      ansible.builtin.uri:
        url: https://boehringer.webspeiseplan.de/index.php?token=2fda60f9e49030893165d438b7b4e946&model=menu&location=1100&languagetype=1&time={{ ansible_date_time["epoch"] }}000
        method: GET
        return_content: true
        validate_certs: false
        headers:
          Host: boehringer.webspeiseplan.de
          Referer: https://boehringer.webspeiseplan.de/Menu
      register: plan_daten

    - name: Extrahiere die Plan Daten für diese und nächste Woche
      ansible.builtin.set_fact:
        mir2: '{{ mir2 | default([]) + [item] }}'
      with_items: '{{ (plan_daten.content | from_json).content }}'
      when: item.speiseplanAdvanced.titel == "Ingelheim MIR 2"

    - name: Extrahiere die Daten für diese Woche
      ansible.builtin.set_fact:
        mir2: '{{ mir2[0] }}'

    - name: Hole den aktuellen Tag
      ansible.builtin.set_fact:
        datum_heute: '{{ ansible_date_time["iso8601"].split("T")[0] }}T00:00:00'
        jahr_heute: '{{ ansible_date_time["iso8601"].split("T")[0].split("-")[0] }}'
        monat_heute: '{{ ansible_date_time["iso8601"].split("T")[0].split("-")[1] }}'
        tag_heute: '{{ ansible_date_time["iso8601"].split("T")[0].split("-")[2] }}'
        gericht_daten: '{{ mir2.speiseplanGerichtData }}'

    - debug:
        msg: 'Tag: {{ tag_heute }} Monat: {{ monat_heute }} Jahr: {{ jahr_heute }}'

    - name: Temporärer Override des Datums
      ansible.builtin.set_fact:
        datum_heute: '2022-08-29T00:00:00'
        jahr_heute: '2022'
        monat_heute: '08'
        tag_heute: '29'

    - name: Extrahiere heutige Gerichte
      ansible.builtin.set_fact:
        essen_heute: |
          {{ essen_heute | default([]) + [{
              "gericht_name":item.speiseplanAdvancedGericht.gerichtname,
              "preis": (item.zusatzinformationen.mitarbeiterpreisDecimal2 |string).replace(".", ",")+"€"
            }]
          }}
      with_items: '{{ gericht_daten | list }}'
      when: item.speiseplanAdvancedGericht.datum == datum_heute

    - name: Create Adaptive Card
      ansible.builtin.template:
        src: 'adaptiveCard.json.j2'
        dest: './adaptiveCard.json'
        mode: 0600

    - name: Send mir eine Email mit der Speiseplan adaptive card
      community.general.mail:
        host: '{{ smtp_server }}'
        port: '{{ smtp_port }}'
        subject: Speiseplan
        username: '{{ smtp_user }}'
        password: '{{ smtp_pass }}'
        body: Hallo, hier ist der Speiseplan
        to:
          - Patrick Pfurtscheller <patrick@pfurtscheller.org>
        attach:
          - ./adaptiveCard.json
        charset: utf-8
      delegate_to: localhost
