---
- name: Speiseplan Benachrichtigung
  hosts: all
  connection: local
  vars:
    test: '{{ TEST | bool | default(false) }}'
    time_override: '{{ TIME_OVERRIDE | bool | default(false) }}'
    override:
      tag: '{{ OVERRIDE_TAG | default("") }}'
      monat: '{{ OVERRIDE_MONAT | default("") }}'
      jahr: '{{ OVERRIDE_JAHR | default("") }}'
  tasks:
    - name: Binde Tasks ein, wenn heute ein Wochentag ist
      ansible.builtin.include_tasks: 'tasks.yml'
      when: ( ansible_date_time.weekday_number > 0 and ansible_date_time.weekday_number < 6 ) or time_override
